### ISSUE TITLE
'Edit TJob' for Jenkins-originated Tjobs redirects to incorrect port

### ISSUE THREAD

**Issue by magdakacmajor** [elastest/elastest#24]
**Environment:** 
Host: RedHat VM
ElasTest platform version: 1.0.0-beta4, launched with options:  `--mode=experimental --server-address=<IP-of-the-VM>`

**To reproduce:**
In Elastest, identify a TJob  created via ElasTest Jenkins plugin. Click "Edit TJob"
Problem: Elastest tries to open Jenkins using port 8080, connection refused

When accessing Jenkins Dashboard from main Elastest menu (Jenkins > Open Jenkins in new tab), the page opens correctly to port 37092.

**Comment by franciscoRdiaz** [comment]
Hi Magda,

It's true, there is a bug. We are working on it to fix it as soon as possible.

Thank you.

**Comment by franciscoRdiaz** [comment]
Hi Magda,

This bug is fixed for the next release. However, you have two options to avoid this bug until we release the new version:

- You can manually update the Jenkins configuration. You have to go to _Manage Jenkins -> Configure System_ and modify the field _Jenkins URL_ with the right Jenkins URL (e.g. http://server_address:37092)

- Or you can also use our dev version of ElasTest (i.e. elastest/platform:dev)

**Comment by magdakacmajor** [comment]
Hi Paco, thanks for the quick action and the workaround tip!
